apiVersion: v2
name: pr-preview
description: Trainyard — ephemeral PR preview environments for Kubernetes
type: application
version: 1.1.1
appVersion: "0.1.2"
keywords:
  - preview
  - ephemeral
  - pull-request
  - kubernetes
  - trainyard
home: https://github.com/Emilvorre/trainyard
sources:
  - https://github.com/Emilvorre/trainyard
maintainers:
  - name: EmilVorre
    url: https://github.com/Emilvorre
