package setup

import (
	"fmt"
	"strings"
	"time"
)

const k3sConfigPath = "/etc/rancher/k3s/config.yaml"

// k3sConfig is written before install so k3s picks it up on first boot.
const k3sConfigTemplate = `# Generated by yard setup 
disable:
	- traefik
`

func installK3s() error {
	// Write config first so k3s starts with Traefik disabled
	if err := writeFile(k3sConfigPath, k3sConfigTemplate, 0644); err != nil {
		return fmt.Errorf("failed k3s config: %w", err)
	}

	// Download and run the official install script
	if err := run("sh", "-c",
		"curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 sh -s - --disable=traefik",
	); err != nil {
		return fmt.Errorf("k3s install failed: %w", err)
	}

	// Wait for k3s to be ready (up to 60s)
	return waitForK3s(60)
}

func waitForK3s(timeoutSeconds int) error {
	deadline := time.Now().Add(time.Duration(timeoutSeconds) * time.Second)
	for time.Now().Before(deadline) {
		out, err := runOutput("k3s", "kubectl", "get", "nodes", "--no-headers")
		if err == nil && strings.Contains(out, "Ready") {
			return nil
		}
		time.Sleep(3 * time.Second)
	}
	return fmt.Errorf("k3s did not become ready within %ds", timeoutSeconds)
}

func k3sRunning() bool {
	err := runSilent("systemctl", "is-active", "--quiet", "k3s")
	return err == nil
}
