package setup

import "fmt"

const nginxSiteTemplate = `# Generated by yard setup
# Proxies *.%s to k3s Nginx Ingress on port %d
 
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
 
server {
    listen 80;
    server_name *.%s;
 
    location / {
        proxy_pass         http://127.0.0.1:%d;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        $connection_upgrade;
        proxy_read_timeout 120s;
    }
}
 
server {
    listen 443 ssl;
    server_name *.%s;
 
    ssl_certificate     /etc/letsencrypt/live/%s/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/%s/privkey.pem;
 
    location / {
        proxy_pass         http://127.0.0.1:%d;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        $connection_upgrade;
        proxy_read_timeout 120s;
    }
}
`

func writeNginxSiteConfig(domain string, httpPort int) error {
	// domain = "preview.vorre.dev", httpPort = 31540
	config := fmt.Sprintf(nginxSiteTemplate,
		domain,   // map comment
		httpPort, // comment
		domain,   // server_name *.domain (http)
		httpPort, // proxy_pass port (http)
		domain,   // server_name *.domain (https)
		domain,   // ssl_certificate path
		domain,   // ssl_certificate_key path
		httpPort, // proxy_pass port (https) — still routes to k3s HTTP port; TLS terminates here
	)

	sitePath := fmt.Sprintf("/etc/nginx/sites-available/trainyard-%s", domain)
	enabledPath := fmt.Sprintf("/etc/nginx/sites-enabled/trainyard-%s", domain)

	if err := writeFile(sitePath, config, 0644); err != nil {
		return fmt.Errorf("writing nginx site config: %w", err)
	}

	// Symlink into sites-enabled
	// Remove stale symlink if exists
	runSilent("rm", "-f", enabledPath)
	if err := runSilent("ln", "-s", sitePath, enabledPath); err != nil {
		return fmt.Errorf("enabling nginx site: %w", err)
	}

	// Test config
	if err := runSilent("nginx", "-t"); err != nil {
		return fmt.Errorf("nginx config test failed: %w", err)
	}

	return runSilent("systemctl", "reload", "nginx")
}
