apiVersion: v1
kind: ServiceAccount
metadata:
  name: trainyard-cleanup
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: trainyard-cleanup
    app.kubernetes.io/managed-by: Helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trainyard-cleanup
  labels:
    app.kubernetes.io/name: trainyard-cleanup
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trainyard-cleanup
  labels:
    app.kubernetes.io/name: trainyard-cleanup
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trainyard-cleanup
subjects:
  - kind: ServiceAccount
    name: trainyard-cleanup
    namespace: {{ .Values.namespace }}