package scaffold

import (
	"strings"
	"testing"
)

func TestRenderPreviewConfig_ContainsHeader(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackSingle
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "# Generated by yard init") {
		t.Error("expected generated header comment")
	}
	if !strings.Contains(out, "https://github.com/Emilvorre/trainyard") {
		t.Error("expected docs URL in header")
	}
}

func TestRenderPreviewConfig_Domain(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Domain = "preview.example.com"
	cfg.Stack = StackSingle
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "domain: preview.example.com") {
		t.Errorf("expected domain in output, got:\n%s", out)
	}
}

func TestRenderPreviewConfig_IngressTLS(t *testing.T) {
	cfg := DefaultConfig()
	cfg.TLS = true
	cfg.IngressClass = "nginx"
	cfg.Stack = StackSingle
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "tls: true") {
		t.Error("expected tls: true in output")
	}
	if !strings.Contains(out, "class: nginx") {
		t.Error("expected class: nginx in output")
	}
}

func TestRenderPreviewConfig_TLSFalse(t *testing.T) {
	cfg := DefaultConfig()
	cfg.TLS = false
	cfg.Stack = StackSingle
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "tls: false") {
		t.Error("expected tls: false in output")
	}
}

func TestRenderPreviewConfig_Label(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Label = "deploy-preview"
	cfg.Stack = StackSingle
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "label: deploy-preview") {
		t.Errorf("expected custom label in output, got:\n%s", out)
	}
}

func TestRenderPreviewConfig_SingleService(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackSingle
	cfg.AppPort = 3000
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "name: app") {
		t.Error("expected service name app")
	}
	if !strings.Contains(out, "port: 3000") {
		t.Error("expected port 3000")
	}
	if !strings.Contains(out, "public: true") {
		t.Error("expected public: true")
	}
	if !strings.Contains(out, `subdomain: "pr-{number}"`) {
		t.Error("expected subdomain pr-{number}")
	}
	if !strings.Contains(out, "dependsOn: []") {
		t.Error("expected empty dependsOn")
	}
}

func TestRenderPreviewConfig_ServiceWithImage(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackAppDB
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	// db service uses image, not build
	if !strings.Contains(out, "image: postgres:16-alpine") {
		t.Error("expected postgres image in output")
	}
	// image services should not have a build block
	lines := strings.Split(out, "\n")
	inDBService := false
	for _, line := range lines {
		if strings.Contains(line, "name: db") {
			inDBService = true
		}
		if inDBService && strings.Contains(line, "build:") {
			t.Error("db service with image should not have build block")
			break
		}
		// next service resets context
		if inDBService && strings.HasPrefix(strings.TrimSpace(line), "- name:") && !strings.Contains(line, "db") {
			break
		}
	}
}

func TestRenderPreviewConfig_ServiceWithBuild(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackSingle
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "build:") {
		t.Error("expected build block for service without image")
	}
	if !strings.Contains(out, "context: .") {
		t.Error("expected build context")
	}
	if !strings.Contains(out, "dockerfile: Dockerfile") {
		t.Error("expected default Dockerfile")
	}
}

func TestRenderPreviewConfig_CustomDockerfile(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackFrontendBackend
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "dockerfile: frontend/Dockerfile") {
		t.Error("expected frontend/Dockerfile in output")
	}
	if !strings.Contains(out, "dockerfile: backend/Dockerfile") {
		t.Error("expected backend/Dockerfile in output")
	}
}

func TestRenderPreviewConfig_DependsOn(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackAppDB
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "- db") {
		t.Error("expected db in dependsOn list")
	}
}

func TestRenderPreviewConfig_EnvVars(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackAppDB
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, "DATABASE_URL") {
		t.Error("expected DATABASE_URL env var")
	}
	if !strings.Contains(out, "postgres://postgres:postgres@db:5432/app") {
		t.Error("expected postgres connection string")
	}
}

func TestRenderPreviewConfig_ResourceDefaults(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackSingle
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.Contains(out, `cpu: "250m"`) {
		t.Error("expected default cpu limit 250m")
	}
	if !strings.Contains(out, `memory: "128Mi"`) {
		t.Error("expected default memory limit 128Mi")
	}
}

func TestRenderPreviewConfig_PrivateServiceNoSubdomain(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackFrontendBackend
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	// backend is private — should not have subdomain
	lines := strings.Split(out, "\n")
	inBackend := false
	for _, line := range lines {
		if strings.Contains(line, "name: backend") {
			inBackend = true
		}
		if inBackend && strings.Contains(line, "subdomain:") {
			t.Error("private backend service should not have subdomain")
			break
		}
		if inBackend && strings.Contains(line, "name: frontend") {
			break
		}
	}
}

func TestRenderPreviewConfig_EndsWithNewline(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackSingle
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	if !strings.HasSuffix(out, "\n") {
		t.Error("expected output to end with newline")
	}
}

func TestRenderPreviewConfig_NoTrailingBlankLines(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Stack = StackSingle
	cfg.Services = ServicesForStack(cfg)

	out := RenderPreviewConfig(cfg)

	// should end with exactly one newline, not multiple
	if strings.HasSuffix(out, "\n\n") {
		t.Error("expected no trailing blank lines")
	}
}
