package scaffold

import (
	"fmt"
	"strings"
)

func RenderPreviewConfig(cfg Config) string {
	var b strings.Builder

	b.WriteString("# Generated by yard init — edit as needed\n")
	b.WriteString("# Docs: https://github.com/Emilvorre/trainyard\n\n")
	b.WriteString("app:\n")
	b.WriteString(fmt.Sprintf("  domain: %s\n\n", cfg.Domain))
	b.WriteString("ingress:\n")
	b.WriteString(fmt.Sprintf("  tls: %v\n", cfg.TLS))
	b.WriteString(fmt.Sprintf("  class: %s\n\n", cfg.IngressClass))
	b.WriteString(fmt.Sprintf("label: %s\n\n", cfg.Label))
	b.WriteString("services:\n")

	for _, svc := range cfg.Services {
		b.WriteString(fmt.Sprintf("  - name: %s\n", svc.Name))
		if svc.Image != "" {
			b.WriteString(fmt.Sprintf("    image: %s\n", svc.Image))
		} else {
			b.WriteString("    build:\n")
			b.WriteString("      context: .\n")
			df := svc.Dockerfile
			if df == "" {
				df = "Dockerfile"
			}
			b.WriteString(fmt.Sprintf("      dockerfile: %s\n", df))
		}
		b.WriteString(fmt.Sprintf("    port: %d\n", svc.Port))
		b.WriteString(fmt.Sprintf("    public: %v\n", svc.Public))
		if svc.Public && svc.Subdomain != "" {
			b.WriteString(fmt.Sprintf("    subdomain: \"%s\"\n", svc.Subdomain))
		}
		b.WriteString("    replicas: 1\n")
		b.WriteString("    resources:\n")
		b.WriteString("      limits:\n")
		cpu := svc.CPU
		if cpu == "" {
			cpu = "250m"
		}
		mem := svc.Memory
		if mem == "" {
			mem = "128Mi"
		}
		b.WriteString(fmt.Sprintf("        cpu: \"%s\"\n", cpu))
		b.WriteString(fmt.Sprintf("        memory: \"%s\"\n", mem))
		if len(svc.EnvVars) > 0 {
			b.WriteString("    env:\n")
			for _, e := range svc.EnvVars {
				b.WriteString(fmt.Sprintf("      - name: %s\n", e.Name))
				b.WriteString(fmt.Sprintf("        value: \"%s\"\n", e.Value))
			}
		}
		b.WriteString("    dependsOn:")
		if len(svc.DependsOn) == 0 {
			b.WriteString(" []\n")
		} else {
			b.WriteString("\n")
			for _, dep := range svc.DependsOn {
				b.WriteString(fmt.Sprintf("      - %s\n", dep))
			}
		}
		b.WriteString("\n")
	}

	return strings.TrimRight(b.String(), "\n") + "\n"
}
