package scaffold

import (
	"strings"
	"testing"
)

func TestRenderWorkflow_ContainsHeader(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "# Generated by yard init") {
		t.Error("expected generated header comment")
	}
}

func TestRenderWorkflow_Name(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "name: PR Preview") {
		t.Error("expected workflow name PR Preview")
	}
}

func TestRenderWorkflow_Triggers(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	for _, trigger := range []string{"opened", "synchronize", "reopened", "labeled", "unlabeled", "closed"} {
		if !strings.Contains(out, "- "+trigger) {
			t.Errorf("expected pull_request trigger %s", trigger)
		}
	}
}

func TestRenderWorkflow_DeployJob(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "deploy:") {
		t.Error("expected deploy job")
	}
	if !strings.Contains(out, "deploy-on-label:") {
		t.Error("expected deploy-on-label job")
	}
}

func TestRenderWorkflow_TeardownJob(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "teardown:") {
		t.Error("expected teardown job")
	}
}

func TestRenderWorkflow_UsesTrainyardWorkflows(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "Emilvorre/trainyard/.github/workflows/deploy.yml@main") {
		t.Error("expected deploy workflow reference")
	}
	if !strings.Contains(out, "Emilvorre/trainyard/.github/workflows/teardown.yml@main") {
		t.Error("expected teardown workflow reference")
	}
}

func TestRenderWorkflow_KubeConfigSecret(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}") {
		t.Error("expected KUBE_CONFIG secret reference")
	}
}

func TestRenderWorkflow_CustomLabel(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Label = "deploy-preview"

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "deploy-preview") {
		t.Errorf("expected custom label deploy-preview in workflow, got:\n%s", out)
	}
	// default label should not appear
	if strings.Contains(out, "'preview'") {
		t.Error("expected default label to be replaced by custom label")
	}
}

func TestRenderWorkflow_DefaultLabel(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "'preview'") {
		t.Error("expected default label preview in workflow conditions")
	}
}

func TestRenderWorkflow_DeployConditionExcludesClosed(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	// deploy job should guard against closed PRs
	if !strings.Contains(out, "github.event.action != 'closed'") {
		t.Error("expected deploy job to exclude closed PRs")
	}
}

func TestRenderWorkflow_TeardownConditionIncludesClosed(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "github.event.action == 'closed'") {
		t.Error("expected teardown job to trigger on closed PRs")
	}
}

func TestRenderWorkflow_TeardownConditionIncludesUnlabeled(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.Contains(out, "github.event.action == 'unlabeled'") {
		t.Error("expected teardown job to trigger on unlabeled")
	}
}

func TestRenderWorkflow_EndsWithNewline(t *testing.T) {
	cfg := DefaultConfig()

	out := RenderWorkflow(cfg)

	if !strings.HasSuffix(out, "\n") {
		t.Error("expected workflow output to end with newline")
	}
}
