package scaffold

import (
	"fmt"
	"strings"
)

const TrainyardRepo = "Emilvorre/trainyard"
const TrainyardWorkflowRef = "main"

func RenderWorkflow(cfg Config) string {
	deployRef := fmt.Sprintf("%s/.github/workflows/deploy.yml@%s", TrainyardRepo, TrainyardWorkflowRef)
	teardownRef := fmt.Sprintf("%s/.github/workflows/teardown.yml@%s", TrainyardRepo, TrainyardWorkflowRef)
	label := cfg.Label

	var b strings.Builder
	b.WriteString("# Generated by yard init\n\n")
	b.WriteString("name: PR Preview\n\n")
	b.WriteString("on:\n  pull_request:\n    types:\n")
	b.WriteString("      - opened\n      - synchronize\n      - reopened\n")
	b.WriteString("      - labeled\n      - unlabeled\n      - closed\n\n")
	b.WriteString("jobs:\n\n")

	b.WriteString("  deploy:\n")
	b.WriteString("    if: |\n")
	b.WriteString(fmt.Sprintf("      contains(github.event.pull_request.labels.*.name, '%s') &&\n", label))
	b.WriteString("      github.event.action != 'closed' &&\n")
	b.WriteString(fmt.Sprintf("      github.event.label.name != '%s'\n", label))
	b.WriteString(fmt.Sprintf("    uses: %s\n", deployRef))
	b.WriteString("    secrets:\n      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}\n\n")

	b.WriteString("  deploy-on-label:\n")
	b.WriteString("    if: |\n")
	b.WriteString("      github.event.action == 'labeled' &&\n")
	b.WriteString(fmt.Sprintf("      github.event.label.name == '%s'\n", label))
	b.WriteString(fmt.Sprintf("    uses: %s\n", deployRef))
	b.WriteString("    secrets:\n      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}\n\n")

	b.WriteString("  teardown:\n")
	b.WriteString("    if: |\n")
	b.WriteString("      github.event.action == 'closed' ||\n")
	b.WriteString("      (\n")
	b.WriteString("        github.event.action == 'unlabeled' &&\n")
	b.WriteString(fmt.Sprintf("        github.event.label.name == '%s'\n", label))
	b.WriteString("      )\n")
	b.WriteString(fmt.Sprintf("    uses: %s\n", teardownRef))
	b.WriteString("    secrets:\n      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}\n")

	return b.String()
}
